# service endpoint
server:
  port: 0

# service name
spring:
  application:
    name: cart
# jpa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true